### ISSUE TITLE
Mime::Type::InvalidMimeType

### ISSUE THREAD

**Issue by gingerlime** [yuki24/rambulance#53]
Hi @yuki24 !

I bumped into a new issue after upgrading to rails 6, producing `Mime::Type::InvalidMimeType` error.

To reproduce, e.g.: `curl -D - -H "Accept: image/apng*/*" https://example.com`

I have a feeling however that this happens before rambulance gets a chance to do anything? even if I add `config.rescue_responses = { "Mime::Type::InvalidMimeType" => :not_acceptable }` it doesn't seem to catch it...

Any tips/thoughts? :) thanks in advance!

**Comment by gingerlime** [comment]
tested with rails 5.2 again with the same request, and in rails 5.2 I get back a normal 200 response, so it used to ignore invalid mime types before and just fell back to some sane default, but I guess not anymore?

**Comment by yuki24** [comment]
Hey @gingerlime, sorry for the delay. I'll look into this issue this weekend.

**Comment by gingerlime** [comment]
Thank you, @yuki24 ! I appreciate it.

**Comment by gingerlime** [comment]
Hi @yuki24 sorry to nag, but was just wondering if you had a chance to look into it? :)

**Comment by yuki24** [comment]
Hey @gingerlime, sorry I didn't have the time to do so last weekend. Hopefully I can do this tomorrow or the day after.

**Comment by gingerlime** [comment]
Thanks for letting me know @yuki24. Please let me know if there's anything I can help with.

**Comment by joker-777** [comment]
We are seeing the same issue. @yuki24 It Would be great if you could fix it.

**Comment by yuki24** [comment]
Apologies for the delay. I should be able to look into it on Saturday.

**Comment by yuki24** [comment]
Just tested this on my side, I think Rails 6 is actually behaving and returning the 406 HTTP status as it should:

```
$ curl -D - -H "Accept: image/apng*/*" https://example.com
HTTP/1.1 406 Not Acceptable
Server: Cowboy
Date: Mon, 11 May 2020 01:25:16 GMT
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
X-Request-Id: 9ad9e710-61f7-4640-b3e6-bc6d0c72d8f1
X-Protected-By: Sqreen
X-Runtime: 0.399095
Strict-Transport-Security: max-age=31536000; includeSubDomains
Content-Length: 0
Via: 1.1 vegur
```

Could one of you describe what you expected to see and what you actually saw?

**Comment by gingerlime** [comment]
@yuki24 thank you.

Yes, rails returns 406 for us in development mode, but if I set `consider_all_requests_local = false` and then run this curl, it returns a 500

```
curl -D - -H "Accept: image/apng*/*" https://example.com
HTTP/2 500
server: nginx/1.17.6
date: Mon, 11 May 2020 11:04:52 GMT
content-type: text/plain
x-request-id: 564210b1-45ab-4079-886a-440f120fbdc8
x-runtime: 0.259087

500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong
```

logs:

```
web_1          | 2020-05-11 11:04:52.036037 FATAL name=Rails message= payload=null tags= named_tags={request_id: 564210b1-45ab-4079-886a-440f120fbdc8, ip: 172.18.0.4, datadog: dd.
trace_id=5807910483349271943 dd.span_id=4532407103869040316 dd.env= dd.version=} duration= process_info=8:puma 001 debug_exceptions.rb:9 exception=[Mime::Type::InvalidMimeType: "i
mage/apng*/*" is not a valid MIME type: /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/http/mime_type.rb:235:in `initialize'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/http/mime_type.rb:143:in `new'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/http/mime_type.rb:143:in `lookup'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/http/mime_type.rb:174:in `parse'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/http/mime_negotiation.rb:47:in `block in accepts'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/request.rb:69:in `fetch'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/request.rb:69:in `fetch_header'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/http/mime_negotiation.rb:41:in `accepts'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/http/mime_negotiation.rb:74:in `block in formats'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/request.rb:69:in `fetch'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/request.rb:69:in `fetch_header'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/http/mime_negotiation.rb:64:in `formats'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/http/mime_negotiation.rb:60:in `format'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_controller/metal/instrumentation.rb:25:in `process_action'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
web_1          | /usr/local/bundle/gems/activerecord-6.0.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/abstract_controller/base.rb:136:in `process'
web_1          | /usr/local/bundle/gems/actionview-6.0.3/lib/action_view/rendering.rb:39:in `process'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_controller/metal.rb:190:in `dispatch'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_controller/metal.rb:254:in `dispatch'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/routing/route_set.rb:33:in `serve'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/journey/router.rb:49:in `block in serve'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/journey/router.rb:32:in `each'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/journey/router.rb:32:in `serve'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/routing/route_set.rb:834:in `call'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1          | /usr/local/bundle/gems/flipper-0.17.2/lib/flipper/middleware/memoizer.rb:62:in `memoized_call'
web_1          | /usr/local/bundle/gems/flipper-0.17.2/lib/flipper/middleware/memoizer.rb:40:in `call'
web_1          | /usr/local/bundle/gems/coverband-4.2.5/lib/coverband/integrations/background_middleware.rb:10:in `call'
web_1          | /usr/local/bundle/gems/rack-attack-6.3.0/lib/rack/attack.rb:111:in `call'
web_1          | /usr/local/bundle/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
web_1          | /usr/local/bundle/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
web_1          | /usr/local/bundle/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
web_1          | /app/lib/locale_middleware.rb:14:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/conditional_get.rb:27:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/middleware/cookies.rb:648:in `call'
web_1          | /usr/local/bundle/gems/activerecord-6.0.3/lib/active_record/migration.rb:567:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
web_1          | /usr/local/bundle/gems/activesupport-6.0.3/lib/active_support/callbacks.rb:101:in `run_callbacks'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
web_1          | /usr/local/bundle/gems/rollbar-2.25.0/lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'
web_1          | /usr/local/bundle/gems/rollbar-2.25.0/lib/rollbar.rb:145:in `scoped'
web_1          | /usr/local/bundle/gems/rollbar-2.25.0/lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web_1          | /usr/local/bundle/gems/rollbar-2.25.0/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
web_1          | /usr/local/bundle/gems/ddtrace-0.34.2/lib/ddtrace/contrib/rails/middlewares.rb:17:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
web_1          | /usr/local/bundle/gems/rails_semantic_logger-4.4.4/lib/rails_semantic_logger/rack/logger.rb:43:in `call_app'
web_1          | /usr/local/bundle/gems/rails_semantic_logger-4.4.4/lib/rails_semantic_logger/rack/logger.rb:26:in `block in call'
web_1          | /usr/local/bundle/gems/semantic_logger-4.6.1/lib/semantic_logger/semantic_logger.rb:386:in `named_tagged'
web_1          | /usr/local/bundle/gems/semantic_logger-4.6.1/lib/semantic_logger/base.rb:194:in `tagged'
web_1          | /usr/local/bundle/gems/rails_semantic_logger-4.4.4/lib/rails_semantic_logger/rack/logger.rb:26:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
web_1          | /usr/local/bundle/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
web_1          | /usr/local/bundle/gems/activesupport-6.0.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/middleware/static.rb:126:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
web_1          | /usr/local/bundle/gems/rack-mini-profiler-2.0.1/lib/mini_profiler/profiler.rb:200:in `call'
web_1          | /usr/local/bundle/gems/ddtrace-0.34.2/lib/ddtrace/contrib/rack/middlewares.rb:85:in `call'
web_1          | /usr/local/bundle/gems/webpacker-5.1.1/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
web_1          | /usr/local/bundle/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
web_1          | /usr/local/bundle/gems/railties-6.0.3/lib/rails/engine.rb:527:in `call'
web_1          | /usr/local/bundle/gems/railties-6.0.3/lib/rails/railtie.rb:190:in `public_send'
web_1          | /usr/local/bundle/gems/railties-6.0.3/lib/rails/railtie.rb:190:in `method_missing'
web_1          | /usr/local/bundle/gems/puma-3.12.4/lib/puma/configuration.rb:227:in `call'
web_1          | /usr/local/bundle/gems/puma-3.12.4/lib/puma/server.rb:675:in `handle_request'
web_1          | /usr/local/bundle/gems/puma-3.12.4/lib/puma/server.rb:476:in `process_client'
web_1          | /usr/local/bundle/gems/puma-3.12.4/lib/puma/server.rb:334:in `block in run'
web_1          | /usr/local/bundle/gems/puma-3.12.4/lib/puma/thread_pool.rb:135:in `block in spawn_thread']
```

When I tried to debug this, it seems like rambulance isn't processing this error at all somehow?

Any tips on how to debug further or figure out what's happening / why? maybe it's something specific to our app, but I'm not sure where to look, so any help would be appreciated.

**Comment by yuki24** [comment]
Thanks all for your patience. This is indeed a bug. I think it makes sense to map this error to `406 Not Acceptable` given that the MIME type is not parseable. I'll send a fix shortly.

**Comment by yuki24** [comment]
Released as https://github.com/yuki24/rambulance/releases/tag/v1.1.0

**Comment by gingerlime** [comment]
Thanks a lot, @yuki24. So glad to see this resolved. I really appreciate it!

**Comment by gingerlime** [comment]
Hi @yuki24 the fix works great for the curl command that I shared, but seems to fail with this

`curl -D - -H 'Content-Type: charset=gbk' https://example.com`

produces a 500 with `Mime::Type::InvalidMimeType: "charset=gbk" is not a valid MIME type`

log:

```
web_1          |   /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
web_1          |   /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/static.rb:126:in `call'
web_1          |   /usr/local/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
web_1          |   /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
web_1          |   /usr/local/bundle/gems/rack-mini-profiler-2.0.1/lib/mini_profiler/profiler.rb:200:in `call'
web_1          |   /usr/local/bundle/gems/ddtrace-0.35.2/lib/ddtrace/contrib/rack/middlewares.rb:85:in `call'
web_1          |   /usr/local/bundle/gems/webpacker-5.1.1/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
web_1          |   /usr/local/bundle/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
web_1          |   /usr/local/bundle/gems/railties-6.0.3.1/lib/rails/engine.rb:527:in `call'
web_1          |   /usr/local/bundle/gems/railties-6.0.3.1/lib/rails/railtie.rb:190:in `public_send'
web_1          |   /usr/local/bundle/gems/railties-6.0.3.1/lib/rails/railtie.rb:190:in `method_missing'
web_1          |   /usr/local/bundle/gems/puma-3.12.4/lib/puma/configuration.rb:227:in `call'
web_1          |   /usr/local/bundle/gems/puma-3.12.4/lib/puma/server.rb:675:in `handle_request'
web_1          |   /usr/local/bundle/gems/puma-3.12.4/lib/puma/server.rb:476:in `process_client'
web_1          |   /usr/local/bundle/gems/puma-3.12.4/lib/puma/server.rb:334:in `block in run'
web_1          |   /usr/local/bundle/gems/puma-3.12.4/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
web_1          | 2020-05-26 10:45:43.318701 FATAL name=Rails message= payload=null tags= named_tags={request_id: 16092acc-a1ff-4cee-9c37-24b1843afa7f, ip: 172.18.0.4, datadog: dd.
env=development dd.service=app dd.trace_id=1696923281124291458 dd.span_id=6698262816142829369} duration= process_info=10:puma 005 debug_exceptions.rb:9 exception=[Mime::Type::I
nvalidMimeType: "charset=gbk" is not a valid MIME type: /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/http/mime_type.rb:235:in `initialize'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/http/mime_type.rb:143:in `new'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/http/mime_type.rb:143:in `lookup'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/http/mime_negotiation.rb:23:in `block in content_mime_type'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/request.rb:69:in `fetch'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/request.rb:69:in `fetch_header'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/http/mime_negotiation.rb:21:in `content_mime_type'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/params_wrapper.rb:277:in `_wrapper_enabled?'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/params_wrapper.rb:244:in `process_action'
web_1          | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/abstract_controller/base.rb:136:in `process'
web_1          | /usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/rendering.rb:39:in `process'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal.rb:190:in `dispatch'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal.rb:254:in `dispatch'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:32:in `each'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:32:in `serve'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:834:in `call'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
web_1          | /usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
web_1          | /usr/local/bundle/gems/flipper-0.17.2/lib/flipper/middleware/memoizer.rb:62:in `memoized_call'
web_1          | /usr/local/bundle/gems/flipper-0.17.2/lib/flipper/middleware/memoizer.rb:40:in `call'
web_1          | /usr/local/bundle/gems/coverband-4.2.5/lib/coverband/integrations/background_middleware.rb:10:in `call'
web_1          | /usr/local/bundle/gems/rack-attack-6.3.1/lib/rack/attack.rb:111:in `call'
web_1          | /usr/local/bundle/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
web_1          | /usr/local/bundle/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
web_1          | /usr/local/bundle/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
web_1          | /app/lib/locale_middleware.rb:14:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/conditional_get.rb:27:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/cookies.rb:648:in `call'
web_1          | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:567:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
web_1          | /usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
web_1          | /usr/local/bundle/gems/rollbar-2.25.0/lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'
web_1          | /usr/local/bundle/gems/rollbar-2.25.0/lib/rollbar.rb:145:in `scoped'
web_1          | /usr/local/bundle/gems/rollbar-2.25.0/lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web_1          | /usr/local/bundle/gems/rollbar-2.25.0/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
web_1          | /usr/local/bundle/gems/ddtrace-0.35.2/lib/ddtrace/contrib/rails/middlewares.rb:17:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
web_1          | /usr/local/bundle/gems/rails_semantic_logger-4.4.4/lib/rails_semantic_logger/rack/logger.rb:43:in `call_app'
web_1          | /usr/local/bundle/gems/rails_semantic_logger-4.4.4/lib/rails_semantic_logger/rack/logger.rb:26:in `block in call'
web_1          | /usr/local/bundle/gems/semantic_logger-4.6.1/lib/semantic_logger/semantic_logger.rb:386:in `named_tagged'
web_1          | /usr/local/bundle/gems/semantic_logger-4.6.1/lib/semantic_logger/base.rb:194:in `tagged'
web_1          | /usr/local/bundle/gems/rails_semantic_logger-4.4.4/lib/rails_semantic_logger/rack/logger.rb:26:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
web_1          | /usr/local/bundle/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
web_1          | /usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/static.rb:126:in `call'
web_1          | /usr/local/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
web_1          | /usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
web_1          | /usr/local/bundle/gems/rack-mini-profiler-2.0.1/lib/mini_profiler/profiler.rb:200:in `call'
web_1          | /usr/local/bundle/gems/ddtrace-0.35.2/lib/ddtrace/contrib/rack/middlewares.rb:85:in `call'
web_1          | /usr/local/bundle/gems/webpacker-5.1.1/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
web_1          | /usr/local/bundle/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
web_1          | /usr/local/bundle/gems/railties-6.0.3.1/lib/rails/engine.rb:527:in `call'
web_1          | /usr/local/bundle/gems/railties-6.0.3.1/lib/rails/railtie.rb:190:in `public_send'
web_1          | /usr/local/bundle/gems/railties-6.0.3.1/lib/rails/railtie.rb:190:in `method_missing'
web_1          | /usr/local/bundle/gems/puma-3.12.4/lib/puma/configuration.rb:227:in `call'
web_1          | /usr/local/bundle/gems/puma-3.12.4/lib/puma/server.rb:675:in `handle_request'
web_1          | /usr/local/bundle/gems/puma-3.12.4/lib/puma/server.rb:476:in `process_client'
web_1          | /usr/local/bundle/gems/puma-3.12.4/lib/puma/server.rb:334:in `block in run'
web_1          | /usr/local/bundle/gems/puma-3.12.4/lib/puma/thread_pool.rb:135:in `block in spawn_thread']
```

**Comment by yuki24** [comment]
@gingerlime The fix only covers the `Accept` header, not the `Content-Type` header. Could you send a pull request? Also, I wonder if fixing all these really make sense... Usually browsers and HTTP clients wouldn't send invalid headers like this.

**Comment by gingerlime** [comment]
Thanks for getting back so quickly @yuki24.

I'd be happy to send a PR, although I'm not that familiar with the codebase. Happy to try anyway if you can guide me in case I get stuck :)

> Also, I wonder if fixing all these really make sense... Usually browsers and HTTP clients wouldn't send invalid headers like this.

Usually, not. But some times they do. If I understand rambulance, it should help catch errors and return nicer responses, rather than 500 though. Perhaps it's not the problem with rambulance, because with Rails < 6 I think it worked fine. But currently some errors don't seem to get caught any more by rambulance, and I thought they should (after all, this is a Mime error that I think is covered by the list of exceptions that Rambulance covers by default? (this list comes from Rails as well as far as I recall). What do you think? am I making some wrong assumptions or do I misunderstand how Rambulance should work? (genuine question).

**Comment by yuki24** [comment]
@gingerlime You should be able to copy the same pattern in https://github.com/yuki24/rambulance/pull/54. It shouldn't require a lot of familiarity to accomplish.

My question is more about how often the majority of users would run into issues this like. You could theoretically construct an HTTP request with malformed data very easily (not just `Content-Type`, but literally anything), but no HTTP server could cover every single contrived edge case that is unrealistic. Have you actually seen a great number of these errors in production?

**Comment by gingerlime** [comment]
> My question is more about how often the majority of users would run into issues this like. You could theoretically construct an HTTP request with malformed data very easily (not just Content-Type, but literally anything), but no HTTP server could cover every single contrived edge case that is unrealistic. Have you actually seen a great number of these errors in production?

I would say that a good web server should allow you to catch those malformed requests gracefully rather than throw a 500 though... A bot/attacker can easily just flood your server with malformed requests (and we do see it from time to time), and I hope there's *some* way (in rails, or a gem like Rambulance) to simply ignore those and return a 406 or something similar rather than 500 ... Is it unreasonable to expect this?

> You should be able to copy the same pattern in #54. It shouldn't require a lot of familiarity to accomplish.

Thank you. I'll give it a shot :)

**Comment by gingerlime** [comment]
@yuki24 I think I need your help with #55 ... I created a test that reproduces the error, but I wasn't sure how to capture the error and handle it... Any pointers?

**Comment by yuki24** [comment]
Let's move this conversation to #55: https://github.com/yuki24/rambulance/pull/55#issuecomment-634820099
